Map<String, String> lang_malai = {
  "马来西亚":"Melayu",
  "复制":"Salinan",
  "添加好友":"Tambah kawan",
  "创建群聊":"Buat sembang kumpulan",
  "取消置顶":"Nyahsemat",
  "置顶该聊天":"Sematkan sembang ini",
  "标为已读":"tanda sebagai telah dibaca",
  "设置成功":"Tetapkan dengan jayanya",
  "已禁言":"diharamkan",
  "已解除禁言":"Tidak diharamkan",
  "已踢出群":"Ditendang keluar dari kumpulan",
  "取消管理员":"Batalkan pentadbir",
  "设为管理员":"Tetapkan sebagai pentadbir",
  "禁言":"Larangan",
  "取消禁言":"Batalkan larangan",
  "踢出群":"Tendang keluar dari kumpulan",
  "收藏成功":"Koleksi berjaya",
  "复制内容":"Salin kandungan",
  "回复":"Balas",
  "撤回消息":"Tarik balik mesej",
  "收藏":"Kumpul",
  "复制成功":"Berjaya disalin",
  "您已禁止权限，需要去设置页面手动开启才能继续":"Anda telah melumpuhkan kebenaran, sila dayakannya!",
  "重试":"Cuba semula",
  "去设置":"Pergi ke Tetapan",
  "确认":"sahkan",
  "好友申请已发送，请耐心等待回复":"Permintaan rakan telah dihantar, sila tunggu dengan sabar untuk balasan",
  "请输入留言":"Sila masukkan mesej",
  "添加":"Tambah",
  "请输入内容":"Sila masukkan",
  "正在搜索中哦～":"Mencari",
  "未查到相关信息":"Tidak dijumpai",
  "搜索好友":"Cari kawan",
  "请输入搜索的内容":"Sila masukkan carian",
  "查找":"Cari",
  "未找到相关好友":"Tiada rakan berkaitan ditemui",
  "请选择视频":"Sila pilih video",
  "请选择图片":"Sila pilih imej",
  "已超过最长录音时间上限，录音已自动停止，需要发送吗":"Masa rakaman maksimum telah. Adakah anda perlu menghantar",
  "取消":"Batal",
  "消息撤回":"Ingat mesej",
  "【图片】":"【gambar】",
  "【语音】":"【Suara】",
  "【文件】":"【dokumen】",
  "【红包】":"【Sampul surat merah】",
  "【转账】":"【pemindahan】",
  "语音时间太短, 发送已被取消":"Masa suara terlalu singkat dan telah dibatalkan",
  "点此发送":"Klik di sini untuk menghantar",
  "取消录制":"Batalkan rakaman",
  "相册":"Album",
  "视频":"Video",
  "拍照":"bergambar",
  "视频聊天":"Sembang video",
  "暂未开放":"Belum buka lagi",
  "语音聊天":"Sembang suara",
  "拍视频":"Ambil video",
  "签名":"Tanda",
  "群主":"Pemilik kumpulan",
  "管理员":"Pentadbir",
  "聊天置顶":"Pin",
  "允许全体发言":"Benarkan semua berbual",
  "允许添加好友":"Benarkan menambah rakan",
  "允许成员退群":"Benarkan untuk pergi",
  "显示群全成员":"Tunjukkan semua ahli kumpulan",
  "请输入消息":"Sila masukkan mesej",
  "发送":"Hantar",
  "正在发送图片,请耐心等待":"Menghantar gambar...",
  "公告":"Notis",
  "消息":"Mesej",
  "你确认要解散群吗?":"Pastikan membubarkan kumpulan?",
  "你确认要退出群吗?":"Pastikan meninggalkan kumpulan?",
  "已解散":"Dibubarkan",
  "已退出":"Keluar",
  "正在上传头像":"Memuat naik avatar",
  "正在更新数据...":"Mengemas kini data...",
  "头像上传失败":"Muat naik avatar gagal",
  "更新头像失败":"Gagal mengemas kini avatar",
  "确认清除聊天记录?":"Sahkan untuk mengosongkan sejarah sembang?",
  "删除失败":"gagal memadam",
  "群聊信息":"Maklumat kumpulan",
  "群聊名称":"Nama kumpulan",
  "群公告":"Notis kumpulan",
  "群成员管理":"Pengurusan kumpulan",
  "群成员":"Ahli kumpulan",
  "群成员添加":"Tambah ahli kumpulan",
  "删除聊天记录":"Padam sejarah",
  "群成员删除":"Pemadaman ahli kumpulan",
  "删除群":"Padam kumpulan",
  "退出群":"Keluar kumpulan",
  "修改备注":"Nota pengubahsuaian",
  "修改昵称":"tukar nama pengguna",
  "个性签名":"Tandatangan",
  "提交":"Hantar",
  "聊天信息":"Maklumat sembang",
  "备注名":"Remark nama",
  "申请中":"Memohon",
  "同意":"Setuju",
  "拒绝":"Tolak",
  "留言":"Mesej",
  "已同意":"Diluluskan",
  "已拒绝":"ditolak",
  "通讯录":"Buku alamat",
  "新的好友":"Kawan baru",
  "我的群聊":"Sembang Kumpulan Saya",
  "转发成功":"Dimajukan dengan jayanya",
  "消息转发":"Pemajuan mesej",
  "好友":"Kawan-kawan",
  "群组":"Kumpulan",
  "暂未加入群聊哦!":"Belum menyertai sembang kumpulan!",
  "好友申请":"Permohonan rakan",
  "我的申请":"Permohonan saya",
  "请输入标题":"Sila masukkan tajuk",
  "请选择群头像":"Sila pilih avatar kumpulan",
  "群创建失败":"Pembuatan kumpulan gagal",
  "群创建成功":"Kumpulan berjaya dibuat",
  "群名称":"Nama kumpulan",
  "请输入群名称":"Sila masukkan nama kumpulan",
  "请输入群公告":"Sila masukkan pengumuman kumpulan",
  "群头像":"Avatar kumpulan",
  "创建":"Buat",
  "请选择成员":"Sila pilih ahli",
  "删除成功":"berjaya dipadamkan",
  "添加成功":"Berjaya ditambahkan",
  "移除":"Alih keluar",
  "请输入用户名":"Sila masukkan nama pengguna",
  "发现":"Temui",
  "请输入密码":"Sila masukkan kata laluan",
  "IM聊天":"Sembang IM",
  "欢迎您!":"Selamat datang!",
  "注册账号":"Daftar akaun",
  "登录":"Log masuk",
  "一键登录":"Log masuk satu klik",
  "版本号":"nombor versi",
  "已有账号？直接登录":"Sudah mempunyai akaun? Log masuk",
  "注册":"Daftar",
  "请输入您的昵称":"Sila masukkan nama panggilan anda",
  "请输入登录密码":"Sila masukkan kata laluan anda",
  "注册成功":"Pendaftaran berjaya",
  "请输入昵称":"Sila masukkan nama panggilan",
  "我的":"saya",
  "再次点击退出":"Klik sekali lagi untuk keluar",
  "IM服务器连接失败":"Sambungan pelayan IM gagal",
  "删除":"Padam",
  "转发":"ke hadapan",
  "关于我们":"Tentang kita",
  "商务合作":"Kerjasama Perniagaan",
  "版本":"Versi",
  "客服":"Khidmat Pelanggan",
  "中文":"cina",
  "英文":"Inggeris",
  "切换语言":"Tukar bahasa",
  "头像修改成功":"Avatar berjaya diubah suai",
  "修改资料":"Edit maklumat",
  "用户ID":"ID Pengguna",
  "用户名":"Nama pengguna",
  "昵称":"nama samaran",
  "换头像":"Tukar avatar",
  "您确定要退出账号吗?":"Adakah anda pasti mahu log keluar?",
  "我的收藏":"Kegemaran saya",
  "安全设置":"Tetapan keselamatan",
  "联系客服":"Hubungi Khidmat Pelanggan",
  "当前版本":"Versi terkini",
  "退出登录":"Log keluar",
  "账号":"Akaun",
  "密码不能少于6位":"Kata laluan mestilah tidak kurang daripada 6 aksara",
  "两次密码输入不一致":"Kedua-dua kata laluan yang dimasukkan tidak konsisten",
  "密码修改成功":"Tetapan semula kata laluan selesai",
  "密码设置":"Tetapan kata laluan",
  "请输入新密码":"Sila masukkan kata laluan baharu",
  "请重新输入新密码":"Sila masukkan semula kata laluan baharu",
  "设置密码":"Tetapkan kata laluan",
};