Map<String, String> lang_yindunixiya = {
  "印度尼西亚":"bahasa Indonesia",
  "复制":"Menyalin",
  "添加好友":"Tambahkan seorang teman",
  "创建群聊":"Buat obrolan grup",
  "取消置顶":"Membuka peniti",
  "置顶该聊天":"Sematkan obrolan ini",
  "标为已读":"tandai sebagai membaca",
  "设置成功":"Pengaturan berhasil",
  "已禁言":"Dilarang",
  "已解除禁言":"Tidak dilarang",
  "已踢出群":"Dikeluarkan dari grup",
  "取消管理员":"Batalkan administrator",
  "设为管理员":"Tetapkan sebagai administrator",
  "禁言":"Melarang",
  "取消禁言":"Batalkan pelarangan",
  "踢出群":"Keluar dari grup",
  "收藏成功":"Pengumpulan berhasil",
  "复制内容":"Salin konten",
  "回复":"Membalas",
  "撤回消息":"Tarik pesan",
  "收藏":"Mengumpulkan",
  "复制成功":"Berhasil disalin",
  "您已禁止权限，需要去设置页面手动开启才能继续":"Anda telah menonaktifkan izin, harap aktifkan!",
  "重试":"Mencoba kembali",
  "去设置":"Pergi ke pengaturan",
  "确认":"Mengonfirmasi",
  "好友申请已发送，请耐心等待回复":"Permintaan pertemanan telah terkirim, harap sabar menunggu balasannya",
  "请输入留言":"Silakan masukkan pesan",
  "添加":"Menambahkan",
  "请输入内容":"Silakan masuk",
  "正在搜索中哦～":"Mencari",
  "未查到相关信息":"Tidak ditemukan",
  "搜索好友":"Cari teman",
  "请输入搜索的内容":"Silakan masukkan pencarian",
  "查找":"Mencari",
  "未找到相关好友":"Tidak ada teman terkait yang ditemukan",
  "请选择视频":"Silakan pilih video",
  "请选择图片":"Silakan pilih gambar",
  "已超过最长录音时间上限，录音已自动停止，需要发送吗":"Waktu perekaman maksimum telah tercapai. Apakah Anda perlu mengirim",
  "取消":"Membatalkan",
  "消息撤回":"Ingat pesan",
  "【图片】":"【gambar】",
  "【语音】":"【Suara】",
  "【文件】":"【dokumen】",
  "【红包】":"【Amplop merah】",
  "【转账】":"【transfer】",
  "语音时间太短, 发送已被取消":"Waktu suara terlalu singkat dan telah dibatalkan",
  "点此发送":"Klik di sini untuk mengirim",
  "取消录制":"Batalkan perekaman",
  "相册":"Album",
  "视频":"Video",
  "拍照":"Foto",
  "视频聊天":"Obrolan video",
  "暂未开放":"Belum terbuka",
  "语音聊天":"Obrolan suara",
  "拍视频":"Ambil video",
  "签名":"Tanda",
  "群主":"Pemilik grup",
  "管理员":"Administrator",
  "聊天置顶":"Pin",
  "允许全体发言":"Izinkan semua orang ngobrol",
  "允许添加好友":"Izinkan menambah teman",
  "允许成员退群":"Izinkan untuk pergi",
  "显示群全成员":"Tampilkan semua anggota grup",
  "请输入消息":"Silakan masukkan pesan",
  "发送":"Mengirim",
  "正在发送图片,请耐心等待":"Mengirim gambar...",
  "公告":"Melihat",
  "消息":"Pesan",
  "你确认要解散群吗?":"Pastikan membubarkan grup?",
  "你确认要退出群吗?":"Pastikan keluar dari grup?",
  "已解散":"Dibubarkan",
  "已退出":"Keluar",
  "正在上传头像":"Mengunggah avatar",
  "正在更新数据...":"Memperbarui data...",
  "头像上传失败":"Pengunggahan avatar gagal",
  "更新头像失败":"Gagal memperbarui avatar",
  "确认清除聊天记录?":"Konfirmasikan untuk menghapus riwayat obrolan?",
  "删除失败":"gagal dihapus",
  "群聊信息":"Informasi grup",
  "群聊名称":"Nama grup",
  "群公告":"Pemberitahuan kelompok",
  "群成员管理":"Manajemen grup",
  "群成员":"Anggota kelompok",
  "群成员添加":"Tambahkan anggota grup",
  "删除聊天记录":"Hapus riwayat",
  "群成员删除":"Penghapusan anggota grup",
  "删除群":"Hapus grup",
  "退出群":"Keluar dari grup",
  "修改备注":"Catatan modifikasi",
  "修改昵称":"ganti nama pengguna",
  "个性签名":"Tanda tangan",
  "提交":"Kirim",
  "聊天信息":"Informasi obrolan",
  "备注名":"Catatan nama",
  "申请中":"Melamar",
  "同意":"Setuju",
  "拒绝":"Menolak",
  "留言":"Pesan",
  "已同意":"Disetujui",
  "已拒绝":"ditolak",
  "通讯录":"Buku alamat",
  "新的好友":"Teman-teman baru",
  "我的群聊":"Obrolan Grup Saya",
  "转发成功":"Berhasil diteruskan",
  "消息转发":"Penerusan pesan",
  "好友":"Teman-teman",
  "群组":"Kelompok",
  "暂未加入群聊哦!":"Belum bergabung dengan obrolan grup!",
  "好友申请":"Aplikasi teman",
  "我的申请":"Lamaran saya",
  "请输入标题":"Silakan masukkan judul",
  "请选择群头像":"Silakan pilih avatar grup",
  "群创建失败":"Pembuatan grup gagal",
  "群创建成功":"Grup berhasil dibuat",
  "群名称":"Nama grup",
  "请输入群名称":"Silakan masukkan nama grup",
  "请输入群公告":"Silakan masukkan pengumuman grup",
  "群头像":"Avatar grup",
  "创建":"Membuat",
  "请选择成员":"Silakan pilih anggota",
  "删除成功":"berhasil dihapus",
  "添加成功":"Berhasil ditambahkan",
  "移除":"Menghapus",
  "请输入用户名":"Silakan masukkan nama pengguna",
  "发现":"Menemukan",
  "请输入密码":"Silakan masukkan kata sandi",
  "IM聊天":"Obrolan saya",
  "欢迎您!":"Selamat datang!",
  "注册账号":"Daftar akun",
  "登录":"Gabung",
  "一键登录":"Masuk sekali klik",
  "版本号":"nomor versi",
  "已有账号？直接登录":"Sudah memiliki akun? Gabung",
  "注册":"Daftar",
  "请输入您的昵称":"Silakan masukkan nama panggilan Anda",
  "请输入登录密码":"Silakan masukkan kata sandi Anda",
  "注册成功":"Registrasi berhasil",
  "请输入昵称":"Silakan masukkan nama panggilan",
  "我的":"Milikku",
  "再次点击退出":"Klik lagi untuk keluar",
  "IM服务器连接失败":"Koneksi server IM gagal",
  "删除":"Menghapus",
  "转发":"Maju",
  "关于我们":"Tentang kami",
  "商务合作":"Kerjasama Bisnis",
  "版本":"Versi: kapan",
  "客服":"Pelayanan pelanggan",
  "中文":"Cina",
  "英文":"Bahasa inggris",
  "切换语言":"Ganti BAHASA",
  "头像修改成功":"Avatar berhasil dimodifikasi",
  "修改资料":"Sunting informasi",
  "用户ID":"identitas pengguna",
  "用户名":"Nama belakang",
  "昵称":"Nama panggilan",
  "换头像":"Mengubah avatar",
  "您确定要退出账号吗?":"Apakah Anda yakin ingin logout?",
  "我的收藏":"Kesukaanku",
  "安全设置":"Pengaturan keamanan",
  "联系客服":"Hubungi Layanan Pelanggan",
  "当前版本":"Versi sekarang",
  "退出登录":"Keluar",
  "账号":"Akun",
  "密码不能少于6位":"Kata sandi tidak boleh kurang dari 6 karakter",
  "两次密码输入不一致":"Kedua kata sandi yang dimasukkan tidak konsisten",
  "密码修改成功":"Penyetelan ulang kata sandi selesai",
  "密码设置":"Pengaturan kata sandi",
  "请输入新密码":"Silakan masukkan kata sandi baru",
  "请重新输入新密码":"Silakan masukkan kembali kata sandi baru",
  "设置密码":"Tetapkan kata sandi",
};