Map<String, String> lang_tuerqi = {
  "土耳其":"Türkçe",
  "复制":"Kopyala",
  "添加好友":"arkadaş ekleme",
  "创建群聊":"Grup sohbeti oluştur",
  "取消置顶":"Sabitlemeyi kaldır",
  "置顶该聊天":"Bu sohbeti sabitle",
  "标为已读":"Okundu olarak işaretle",
  "设置成功":"Başarıyla ayarla",
  "已禁言":"Yasaklandı",
  "已解除禁言":"Yasak kaldırıldı",
  "已踢出群":"Gruptan atıldı",
  "取消管理员":"Yöneticiyi iptal et",
  "设为管理员":"Yönetici olarak ayarla",
  "禁言":"Yasak",
  "取消禁言":"Yasağı kaldır",
  "踢出群":"Gruptan çıkar",
  "收藏成功":"Koleksiyon başarılı",
  "复制内容":"İçeriği kopyala",
  "回复":"Cevap vermek",
  "撤回消息":"Mesajı geri çek",
  "收藏":"TOPLAMAK",
  "复制成功":"Başarıyla kopyalandı",
  "您已禁止权限，需要去设置页面手动开启才能继续":"İzni devre dışı bıraktınız, lütfen etkinleştirin!",
  "重试":"Yeniden dene",
  "去设置":"Ayarlara git",
  "确认":"Onaylamak",
  "好友申请已发送，请耐心等待回复":"Arkadaşlık isteği gönderildi, lütfen cevabı sabırla bekleyin",
  "请输入留言":"Lütfen bir mesaj girin",
  "添加":"Eklemek",
  "请输入内容":"Girin lütfen",
  "正在搜索中哦～":"Aranıyor",
  "未查到相关信息":"Bulunamadı",
  "搜索好友":"Arkadaşlarını ara",
  "请输入搜索的内容":"Lütfen aramaya girin",
  "查找":"Aramak",
  "未找到相关好友":"İlgili arkadaş bulunamadı",
  "请选择视频":"Lütfen bir video seçin",
  "请选择图片":"Lütfen bir resim seçin",
  "已超过最长录音时间上限，录音已自动停止，需要发送吗":"Maksimum kayıt süresi olmuştur. göndermeniz gerekiyor mu",
  "取消":"İptal etmek",
  "消息撤回":"Mesajı geri çağır",
  "【图片】":"【resim】",
  "【语音】":"【Ses】",
  "【文件】":"[belge]",
  "【红包】":"【Kırmızı zarf】",
  "【转账】":"【Aktar】",
  "语音时间太短, 发送已被取消":"Ses süresi çok kısa ve iptal edildi",
  "点此发送":"Göndermek için burayı tıklayın",
  "取消录制":"Kaydı iptal et",
  "相册":"Albüm",
  "视频":"Video",
  "拍照":"Fotoğraf",
  "视频聊天":"Görüntülü sohbet",
  "暂未开放":"Henüz açık değil",
  "语音聊天":"Sesli sohbet",
  "拍视频":"Video çek",
  "签名":"İmza",
  "群主":"Grup sahibi",
  "管理员":"Yönetici",
  "聊天置顶":"Toplu iğne",
  "允许全体发言":"Herkesin sohbet etmesine izin ver",
  "允许添加好友":"Arkadaş eklemeye izin ver",
  "允许成员退群":"Ayrılmaya izin ver",
  "显示群全成员":"Tüm grup üyelerini göster",
  "请输入消息":"Lütfen mesajınızı girin",
  "发送":"Göndermek",
  "正在发送图片,请耐心等待":"Resimler gönderiliyor...",
  "公告":"Fark etme",
  "消息":"İleti",
  "你确认要解散群吗?":"Grubu dağıttığınızdan emin misiniz?",
  "你确认要退出群吗?":"Gruptan ayrıldığınızdan emin misiniz?",
  "已解散":"Dağıldı",
  "已退出":"Çıkıldı",
  "正在上传头像":"Avatar yükleniyor",
  "正在更新数据...":"Veriler güncelleniyor...",
  "头像上传失败":"Avatar yüklemesi başarısız oldu",
  "更新头像失败":"Avatar güncellenemedi",
  "确认清除聊天记录?":"Sohbet geçmişini temizlemeyi onaylıyor musunuz?",
  "删除失败":"silinemedi",
  "群聊信息":"Grup bilgileri",
  "群聊名称":"Grup ismi",
  "群公告":"Grup bildirimi",
  "群成员管理":"Grup yönetimi",
  "群成员":"Grup üyeleri",
  "群成员添加":"Grup üyelerini ekleyin",
  "删除聊天记录":"Geçmişi sil",
  "群成员删除":"Grup üyesi silme",
  "删除群":"Grubu sil",
  "退出群":"Gruptan çık",
  "修改备注":"Değişiklik notları",
  "修改昵称":"Kullanıcı adını değiştir",
  "个性签名":"İmza",
  "提交":"Göndermek",
  "聊天信息":"Sohbet bilgileri",
  "备注名":"Açıklama adı",
  "申请中":"Başvuruyor",
  "同意":"Kabul etmek",
  "拒绝":"Reddetmek",
  "留言":"İleti",
  "已同意":"Onaylı",
  "已拒绝":"Reddedilmiş",
  "通讯录":"Adres defteri",
  "新的好友":"Yeni arkadaşlar",
  "我的群聊":"Grup Sohbetim",
  "转发成功":"Başarıyla iletildi",
  "消息转发":"Mesaj iletme",
  "好友":"Arkadaşlar",
  "群组":"Grup",
  "暂未加入群聊哦!":"Henüz grup sohbetine katılmadınız!",
  "好友申请":"Arkadaş başvurusu",
  "我的申请":"Başvurum",
  "请输入标题":"Lütfen başlığı girin",
  "请选择群头像":"Lütfen bir grup avatarı seçin",
  "群创建失败":"Grup oluşturulamadı",
  "群创建成功":"Grup başarıyla oluşturuldu",
  "群名称":"Grup ismi",
  "请输入群名称":"Lütfen grup adını girin",
  "请输入群公告":"Lütfen grup duyurusunu girin",
  "群头像":"Grup avatarı",
  "创建":"Yaratmak",
  "请选择成员":"Lütfen bir üye seçin",
  "删除成功":"başarıyla silindi",
  "添加成功":"Başarıyla eklendi",
  "移除":"Kaldırmak",
  "请输入用户名":"Lütfen kullanıcı adını girin",
  "发现":"Keşfetmek",
  "请输入密码":"Lütfen şifre giriniz",
  "IM聊天":"anlık mesajlaşma sohbeti",
  "欢迎您!":"Hoş geldin!",
  "注册账号":"Bir hesap oluştur",
  "登录":"Giriş yapmak",
  "一键登录":"Tek tıkla giriş",
  "版本号":"versiyon numarası",
  "已有账号？直接登录":"Zaten hesabınız var mı? Giriş yapmak",
  "注册":"Kayıt olmak",
  "请输入您的昵称":"lütfen takma adınızı giriniz",
  "请输入登录密码":"Şifrenizi giriniz Lütfen",
  "注册成功":"Başarılı Kayıt",
  "请输入昵称":"Lütfen bir takma isim giriniz",
  "我的":"Bana ait",
  "再次点击退出":"Çıkmak için tekrar tıklayın",
  "IM服务器连接失败":"Sohbet sunucusu bağlantısı başarısız oldu",
  "删除":"Silmek",
  "转发":"İleri",
  "关于我们":"Hakkımızda",
  "商务合作":"İşbirliği",
  "版本":"Sürüm",
  "客服":"Müşteri servisi",
  "中文":"Çince",
  "英文":"İngilizce",
  "切换语言":"Dili değiştir",
  "头像修改成功":"Avatar başarıyla değiştirildi",
  "修改资料":"Bilgileri düzenle",
  "用户ID":"Kullanıcı kimliği",
  "用户名":"Kullanıcı adı",
  "昵称":"Takma ad",
  "换头像":"Avatarı değiştir",
  "您确定要退出账号吗?":"Oturumu kapatmak istediğinizden emin misiniz?",
  "我的收藏":"Favorilerim",
  "安全设置":"Güvenlik ayarları",
  "联系客服":"Müşteri Hizmetleriyle İletişime Geçin",
  "当前版本":"Şimdiki versiyonu",
  "退出登录":"Çıkış Yap",
  "账号":"Hesap",
  "密码不能少于6位":"Şifre 6 karakterden az olmamalıdır",
  "两次密码输入不一致":"Girilen iki şifre tutarsız",
  "密码修改成功":"Şifre sıfırlama tamamlandı",
  "密码设置":"Şifre ayarları",
  "请输入新密码":"Lütfen yeni bir şifre girin",
  "请重新输入新密码":"Lütfen yeni şifreyi tekrar girin",
  "设置密码":"Bir şifre belirleyin",
};