Map<String, String> lang_yulan = {
  "越南":"Tiếng Việt",
  "复制":"Sao chép",
  "添加好友":"Thêm bạn",
  "创建群聊":"Tạo cuộc trò chuyện nhóm",
  "取消置顶":"Bỏ ghim",
  "置顶该聊天":"Ghim cuộc trò chuyện này",
  "标为已读":"đánh dấu là đã đọc",
  "设置成功":"Đặt thành công",
  "已禁言":"Bị cấm",
  "已解除禁言":"Không bị cấm",
  "已踢出群":"Bị đuổi khỏi nhóm",
  "取消管理员":"Hủy quản trị viên",
  "设为管理员":"Đặt làm quản trị viên",
  "禁言":"Lệnh cấm",
  "取消禁言":"Bỏ cấm",
  "踢出群":"Đá ra khỏi nhóm",
  "收藏成功":"Bộ sưu tập thành công",
  "复制内容":"Sao chép nội dung",
  "回复":"Hồi đáp",
  "撤回消息":"Rút tin nhắn",
  "收藏":"Sưu tầm",
  "复制成功":"Đã sao chép thành công",
  "您已禁止权限，需要去设置页面手动开启才能继续":"Bạn đã vô hiệu hóa quyền, vui lòng kích hoạt nó!",
  "重试":"Thử lại",
  "去设置":"Đi tới Cài đặt",
  "确认":"Xác nhận",
  "好友申请已发送，请耐心等待回复":"Yêu cầu kết bạn đã được gửi đi, hãy kiên nhẫn chờ đợi phản hồi",
  "请输入留言":"Vui lòng nhập tin nhắn",
  "添加":"Thêm vào",
  "请输入内容":"Vui lòng nhập",
  "正在搜索中哦～":"Đang tìm kiếm",
  "未查到相关信息":"Không tìm thấy",
  "搜索好友":"Tìm kiếm bạn bè",
  "请输入搜索的内容":"Vui lòng nhập tìm kiếm",
  "查找":"Tìm kiếm",
  "未找到相关好友":"Không tìm thấy bạn bè liên quan",
  "请选择视频":"Vui lòng chọn một video",
  "请选择图片":"Vui lòng chọn một hình ảnh",
  "已超过最长录音时间上限，录音已自动停止，需要发送吗":"Thời gian ghi tối đa đã được. Bạn có cần gửi không",
  "取消":"Hủy bỏ",
  "消息撤回":"Thu hồi tin nhắn",
  "【图片】":"【hình ảnh】",
  "【语音】":"【Tiếng nói】",
  "【文件】":"【tài liệu】",
  "【红包】":"[Phong bì đỏ]",
  "【转账】":"【chuyển khoản】",
  "语音时间太短, 发送已被取消":"Thời gian thoại quá ngắn và đã bị hủy",
  "点此发送":"Bấm vào đây để gửi",
  "取消录制":"Hủy ghi âm",
  "相册":"Album",
  "视频":"Băng hình",
  "拍照":"ảnh chụp",
  "视频聊天":"Trò chuyện video",
  "暂未开放":"Chưa mở",
  "语音聊天":"Trò chuyện bằng giọng nói",
  "拍视频":"Quay video",
  "签名":"Dấu hiệu",
  "群主":"Chủ nhóm",
  "管理员":"Người quản lý",
  "聊天置顶":"Ghim",
  "允许全体发言":"Cho phép tất cả trò chuyện",
  "允许添加好友":"Cho phép thêm bạn bè",
  "允许成员退群":"Cho phép rời đi",
  "显示群全成员":"Hiển thị tất cả thành viên nhóm",
  "请输入消息":"Vui lòng nhập tin nhắn",
  "发送":"Gửi",
  "正在发送图片,请耐心等待":"Đang gửi ảnh...",
  "公告":"Để ý",
  "消息":"Tin nhắn",
  "你确认要解散群吗?":"Đảm bảo giải tán nhóm?",
  "你确认要退出群吗?":"Đảm bảo rời khỏi nhóm?",
  "已解散":"Giải tán",
  "已退出":"Đã thoát",
  "正在上传头像":"Đang tải hình đại diện lên",
  "正在更新数据...":"Cập nhật dữ liệu...",
  "头像上传失败":"Tải lên hình đại diện không thành công",
  "更新头像失败":"Không cập nhật được hình đại diện",
  "确认清除聊天记录?":"Xác nhận xóa lịch sử trò chuyện?",
  "删除失败":"không thể xóa",
  "群聊信息":"Thông tin nhóm",
  "群聊名称":"Tên nhóm",
  "群公告":"Thông báo nhóm",
  "群成员管理":"Quản lý nhóm",
  "群成员":"Thành viên nhóm",
  "群成员添加":"Thêm thành viên nhóm",
  "删除聊天记录":"Xóa lịch sử",
  "群成员删除":"Xóa thành viên nhóm",
  "删除群":"Xóa nhóm",
  "退出群":"Thoát khỏi nhóm",
  "修改备注":"Ghi chú sửa đổi",
  "修改昵称":"thay đổi tên người dùng",
  "个性签名":"Chữ ký",
  "提交":"Nộp",
  "聊天信息":"Thông tin trò chuyện",
  "备注名":"Tên nhận xét",
  "申请中":"Áp dụng",
  "同意":"Đồng ý",
  "拒绝":"Từ chối",
  "留言":"Tin nhắn",
  "已同意":"Tán thành",
  "已拒绝":"vật bị loại bỏ",
  "通讯录":"Sổ địa chỉ",
  "新的好友":"Những người bạn mới",
  "我的群聊":"Trò chuyện nhóm của tôi",
  "转发成功":"Đã chuyển tiếp thành công",
  "消息转发":"Chuyển tiếp tin nhắn",
  "好友":"Bạn",
  "群组":"Nhóm",
  "暂未加入群聊哦!":"Chưa tham gia trò chuyện nhóm!",
  "好友申请":"Ứng dụng kết bạn",
  "我的申请":"Ứng dụng của tôi",
  "请输入标题":"Vui lòng nhập tiêu đề",
  "请选择群头像":"Vui lòng chọn hình đại diện của nhóm",
  "群创建失败":"Tạo nhóm không thành công",
  "群创建成功":"Nhóm được tạo thành công",
  "群名称":"Tên nhóm",
  "请输入群名称":"Vui lòng nhập tên nhóm",
  "请输入群公告":"Vui lòng nhập thông báo nhóm",
  "群头像":"Hình đại diện nhóm",
  "创建":"Tạo nên",
  "请选择成员":"Vui lòng chọn một thành viên",
  "删除成功":"đã xóa thành công",
  "添加成功":"Thêm thành công",
  "移除":"Di dời",
  "请输入用户名":"Vui lòng nhập tên người dùng",
  "发现":"Phát hiện",
  "请输入密码":"Xin vui lòng nhập mật khẩu",
  "IM聊天":"Trò chuyện IM",
  "欢迎您!":"Chào mừng!",
  "注册账号":"Đăng ký tài khoản",
  "登录":"Đăng nhập",
  "一键登录":"Đăng nhập bằng một cú nhấp chuột",
  "版本号":"số phiên bản",
  "已有账号？直接登录":"Bạn co săn san để tạo một tai khoản? Đăng nhập",
  "注册":"Đăng ký",
  "请输入您的昵称":"vui lòng nhập nickname của bạn",
  "请输入登录密码":"Vui lòng nhập mật khẩu của bạn",
  "注册成功":"Đăng ký thành công",
  "请输入昵称":"Hãy nhập một nickname",
  "我的":"Của tôi",
  "再次点击退出":"Nhấn lần nữa để thoát",
  "IM服务器连接失败":"Kết nối máy chủ IM không thành công",
  "删除":"Xóa bỏ",
  "转发":"Phía trước",
  "关于我们":"Về chúng tôi",
  "商务合作":"Hợp tác kinh doanh",
  "版本":"Phiên bản",
  "客服":"Dịch vụ khách hàng",
  "中文":"người Trung Quốc",
  "英文":"Tiếng Anh",
  "切换语言":"Thay đổi ngôn ngữ",
  "头像修改成功":"Avatar được sửa đổi thành công",
  "修改资料":"Chỉnh sửa thông tin",
  "用户ID":"Tên người dùng",
  "用户名":"tên tài khoản",
  "昵称":"Tên nick",
  "换头像":"Thay đổi hình đại diện",
  "您确定要退出账号吗?":"Bạn có chắc chắn bạn muốn thoát?",
  "我的收藏":"Mục yêu thích của tôi",
  "安全设置":"Cài đặt hệ thống bảo vệ",
  "联系客服":"liên hệ với dịch vụ khách hàng",
  "当前版本":"Phiên bản hiện tại",
  "退出登录":"Đăng xuất",
  "账号":"Tài khoản",
  "密码不能少于6位":"Mật khẩu không được ít hơn 6 ký tự",
  "两次密码输入不一致":"Hai mật khẩu đã nhập không nhất quán",
  "密码修改成功":"Đặt lại mật khẩu hoàn tất",
  "密码设置":"Cài đặt mật khẩu",
  "请输入新密码":"Vui lòng nhập mật khẩu mới",
  "请重新输入新密码":"Vui lòng nhập lại mật khẩu mới",
  "设置密码":"Đặt mật khẩu",
};